#!/usr/bin/env python3
"""Run a reproducible API load test and record measured results."""

import argparse
import csv
import os
import random
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import httpx


def generate_csv(path: Path, rows: int) -> None:
    currencies = ("USD", "EUR", "GBP", "JPY", "AUD", "CAD")
    types = ("CREDIT", "DEBIT")
    start = datetime(2026, 1, 1, tzinfo=timezone.utc)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["transaction_id", "account_id", "type", "amount", "currency", "timestamp"])
        for index in range(1, rows + 1):
            writer.writerow([
                f"TXN-PERF-{index:010d}",
                f"ACC-{random.randint(1, 1000):04d}",
                random.choice(types),
                f"{random.uniform(0.01, 100_000):.2f}",
                random.choice(currencies),
                (start + timedelta(seconds=index)).isoformat(),
            ])


def wait_for_import(client: httpx.Client, base_url: str, api_key: str, import_id: str, timeout: int) -> dict:
    started = time.monotonic()
    while time.monotonic() - started < timeout:
        response = client.get(
            f"{base_url}/api/v1/imports/{import_id}",
            headers={"X-API-Key": api_key},
        )
        response.raise_for_status()
        status = response.json()
        if status["status"] in {"COMPLETED", "FAILED"}:
            return status
        time.sleep(2)
    raise TimeoutError(f"Import {import_id} did not finish within {timeout} seconds")


def run_locust(host: str, api_key: str, users: int, spawn_rate: int, duration: str, output_prefix: Path) -> int:
    environment = os.environ.copy()
    environment["API_KEY"] = api_key
    command = [
        sys.executable, "-m", "locust", "-f", "load_test/locustfile.py",
        "--host", host, "--users", str(users), "--spawn-rate", str(spawn_rate),
        "--run-time", duration, "--headless", "--csv", str(output_prefix),
    ]
    return subprocess.run(command, check=False, env=environment).returncode


def write_report(path: Path, metadata: dict, stats: list[dict], import_status: dict) -> None:
    lines = [
        "# Measured Performance Results", "",
        "This report was generated by `load_test/run_performance_tests.py`.",
        "All values below are measured from the recorded run.", "", "## Configuration", "",
    ]
    lines.extend(f"- **{key}**: {value}" for key, value in metadata.items())
    lines.extend([
        "", "## Locust Statistics", "",
        "| Name | Requests | Failures | Average ms | p50 ms | p95 ms | p99 ms |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ])
    for row in stats:
        lines.append(
            f"| {row['Name']} | {row['Request Count']} | {row['Failure Count']} | "
            f"{row['Average Response Time']} | {row['50%']} | {row['95%']} | {row['99%']} |"
        )
    lines.extend([
        "", "## Large Import", "",
        f"- **Status**: {import_status['status']}",
        f"- **Rows**: {import_status.get('total_rows')}",
        f"- **Processed**: {import_status.get('processed_rows')}",
        f"- **Successful**: {import_status.get('successful_rows')}",
        f"- **Failed**: {import_status.get('failed_rows')}",
        "",
        "Locust counts HTTP 429 responses as failures. Under a single API key, "
        "those responses demonstrate the configured distributed rate limit rather "
        "than an application crash; repeat with multiple keys to measure unrestricted throughput.",
    ])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default=os.getenv("API_HOST", "http://localhost:8000"))
    parser.add_argument("--api-key", default=os.getenv("API_KEY"))
    parser.add_argument("--users", type=int, default=50)
    parser.add_argument("--spawn-rate", type=int, default=10)
    parser.add_argument("--duration", default="60s")
    parser.add_argument("--large-rows", type=int, default=100_000)
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--report", type=Path, default=Path("load_test/PERFORMANCE_RESULTS.md"))
    args = parser.parse_args()
    if not args.api_key:
        parser.error("provide --api-key or set API_KEY")

    base_url = args.host.rstrip("/")
    with tempfile.TemporaryDirectory(prefix="transaction-platform-perf-") as temp_dir:
        temp_path = Path(temp_dir)
        large_csv = temp_path / "large.csv"
        generate_csv(large_csv, args.large_rows)
        with httpx.Client(timeout=30) as client:
            with large_csv.open("rb") as upload:
                response = client.post(
                    f"{base_url}/api/v1/imports",
                    headers={"X-API-Key": args.api_key},
                    files={"file": (large_csv.name, upload, "text/csv")},
                )
            response.raise_for_status()
            import_id = response.json()["import_id"]
            import_started = time.monotonic()
            import_status = wait_for_import(client, base_url, args.api_key, import_id, args.timeout)
            import_elapsed = time.monotonic() - import_started

            prefix = temp_path / "locust"
            locust_started = time.monotonic()
            locust_exit_code = run_locust(
                base_url, args.api_key, args.users, args.spawn_rate, args.duration, prefix
            )
            locust_elapsed = time.monotonic() - locust_started

        with Path(f"{prefix}_stats.csv").open(newline="", encoding="utf-8") as handle:
            stats = list(csv.DictReader(handle))

    metadata = {
        "Date UTC": datetime.now(timezone.utc).isoformat(),
        "Host": base_url,
        "Users": args.users,
        "Spawn rate": args.spawn_rate,
        "Duration": args.duration,
        "Large rows": args.large_rows,
        "Import processing seconds": f"{import_elapsed:.2f}",
        "Locust runtime seconds": f"{locust_elapsed:.2f}",
        "Locust exit code": locust_exit_code,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    write_report(args.report, metadata, stats, import_status)
    print({"report": str(args.report), "import": import_status})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
